# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  avm_config = release
endif
ifeq ($(config),debug)
  avm_config = debug
endif
ifeq ($(config),profile)
  avm_config = profile
endif
ifeq ($(config),final)
  avm_config = final
endif

PROJECTS := avm

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

avm:
ifneq (,$(avm_config))
	@echo "==== Building avm ($(avm_config)) ===="
	@${MAKE} --no-print-directory -C . -f avm.make config=$(avm_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f avm.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo "  profile"
	@echo "  final"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   avm"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"