# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  utils_config = release
  avm_config = release

else ifeq ($(config),debug)
  utils_config = debug
  avm_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := utils avm

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

utils:
ifneq (,$(utils_config))
	@echo "==== Building utils ($(utils_config)) ===="
	@${MAKE} --no-print-directory -C . -f utils.make config=$(utils_config)
endif

avm: utils
ifneq (,$(avm_config))
	@echo "==== Building avm ($(avm_config)) ===="
	@${MAKE} --no-print-directory -C . -f avm.make config=$(avm_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f utils.make clean
	@${MAKE} --no-print-directory -C . -f avm.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   utils"
	@echo "   avm"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"